# Generated by Django 5.0.1 on 2024-01-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='job',
            field=models.CharField(choices=[('Malyarchik', 'Malyarchik'), ('', '')], max_length=25),
        ),
    ]
