# Generated by Django 5.0.1 on 2024-01-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0002_alter_worker_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='job',
            field=models.CharField(choices=[('Malyarchik', 'Malyarchik'), ('Quruvchi', 'Quruvchi'), ('Santexnik', 'Santexnik'), ('Elektrik', 'Elektrik'), ('Uy tozalovchi', 'Uy tozalovchi'), ('Avtomobil ustasi', 'Avtomobil ustasi'), ('Yuk tushuruvch', 'Yuk tushuruvchi'), ("Mebil yig'uvchi", "Mebel yig'uvchi"), ('Akfachi', 'Akfachi'), ('Maishiy texnika ustasi', 'Maishiy texnika ustasi')], max_length=25),
        ),
    ]
